
$imports = "";
$exports = "export const images = [";
$galleryPath = ".\public\gallery"
$exportsFilePath = ".\src\app\exports.ts";

"" > $exportsFilePath

$files = Get-ChildItem -Path $galleryPath |`
Where-Object {
    $_.Extension -match "(jpg)|(png)|(jpeg)|(gif)"
}
foreach($file in $files)
{
    $importPath = [System.IO.Path]::GetRelativePath(".\src\app", $file.FullName)
    $symbol = $file.BaseName

    $imports += "import $symbol from '$importPath';`r`n";
    $exports += "`r`n  $symbol,"
}

$exports = $exports.Substring(0, $exports.Length - 1)
$exports += "`r`n];"

"// Generated by exports.ps1`r`n`r`n$imports`r`n`r`n$exports`r`n".Replace("\","/") > $exportsFilePath