const fs = require("fs");
const path = require("path");

generateGalleryImageExports();

function generateGalleryImageExports() {
  let imports = "";
  let exports = "export const images = [";
  const galleryPath = "./public/gallery";
  const exportsFilePath = "./src/app/exports.ts";

  fs.writeFileSync(exportsFilePath, "");

  const files = fs.readdirSync(galleryPath).filter((file) => {
    const extension = path.extname(file).toLowerCase();
    return [".jpg", ".png", ".jpeg", ".gif"].includes(extension);
  });

  files.forEach((file) => {
    const importPath = path.relative("./src/app", path.join(galleryPath, file));
    const symbol = path.parse(file).name;

    imports += `import ${symbol} from '${importPath}';\r\n`;
    exports += `\r\n  ${symbol},`;
  });

  exports = exports.substring(0, exports.length - 1);
  exports += "\r\n];";

  const content = `// Generated by prebuild.js\r\n\r\n${imports}\r\n\r\n${exports}\r\n`;
  fs.writeFileSync(exportsFilePath, content.replace(/\\/g, "/"));
}
