// Generated by exports.ps1

import california from '../public/gallery/california.jpg';
import chiefs_game_1 from '../public/gallery/chiefs_game_1.jpg';
import christmas_party1_2020 from '../public/gallery/christmas_party1_2020.jpg';
import christmas_party2_2020 from '../public/gallery/christmas_party2_2020.jpg';
import christmas_party3_2020 from '../public/gallery/christmas_party3_2020.jpg';
import christmas1_2023 from '../public/gallery/christmas1_2023.jpg';
import christmas2_2023 from '../public/gallery/christmas2_2023.jpg';
import christmas3_2023 from '../public/gallery/christmas3_2023.jpg';
import christmas4_2023 from '../public/gallery/christmas4_2023.jpg';
import disney_1 from '../public/gallery/disney_1.jpg';
import july4th_2023 from '../public/gallery/july4th_2023.jpg';
import kyle_fall_2023 from '../public/gallery/kyle_fall_2023.jpg';
import matt_gandy_wedding from '../public/gallery/matt_gandy_wedding.jpg';
import proposal_1 from '../public/gallery/proposal_1.jpg';
import proposal_2 from '../public/gallery/proposal_2.jpg';
import proposal_3 from '../public/gallery/proposal_3.jpg';
import proposal_4 from '../public/gallery/proposal_4.jpg';
import proposal_5 from '../public/gallery/proposal_5.jpg';
import proposal_6 from '../public/gallery/proposal_6.jpg';
import zion_hike_1 from '../public/gallery/zion_hike_1.jpg';
import zion_hike_2 from '../public/gallery/zion_hike_2.jpg';
import zion_hike_3 from '../public/gallery/zion_hike_3.jpg';


export const images = [
  california,
  chiefs_game_1,
  christmas_party1_2020,
  christmas_party2_2020,
  christmas_party3_2020,
  christmas1_2023,
  christmas2_2023,
  christmas3_2023,
  christmas4_2023,
  disney_1,
  july4th_2023,
  kyle_fall_2023,
  matt_gandy_wedding,
  proposal_1,
  proposal_2,
  proposal_3,
  proposal_4,
  proposal_5,
  proposal_6,
  zion_hike_1,
  zion_hike_2,
  zion_hike_3
];

